package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Sleek Interface Theme - Light Palette (from design specification)
val SleekBackgroundLight = Color(0xFFFDFBFF)
val SleekSurfaceLight = Color(0xFFFFFFFF)
val SleekSurfaceVariantLight = Color(0xFFF3EDF7)
val SleekPrimaryLight = Color(0xFF6750A4)
val SleekOnPrimaryLight = Color(0xFFFFFFFF)
val SleekPrimaryContainerLight = Color(0xFFEADDFF)
val SleekOnPrimaryContainerLight = Color(0xFF21005D)
val SleekSecondaryLight = Color(0xFF625B71)
val SleekOnSecondaryLight = Color(0xFFFFFFFF)
val SleekSecondaryContainerLight = Color(0xFFE8DEF8)
val SleekOnSecondaryContainerLight = Color(0xFF1D192B)
val SleekTertiaryLight = Color(0xFF7D5260)
val SleekTertiaryContainerLight = Color(0xFFFFD8E4)
val SleekOutlineLight = Color(0xFFCAC4D0)
val SleekOutlineVariantLight = Color(0xFFE7E0EC)
val SleekTextPrimaryLight = Color(0xFF1C1B1F)
val SleekTextSecondaryLight = Color(0xFF49454F)

// Sleek Interface Theme - Dark Palette
val SleekBackgroundDark = Color(0xFF141218)
val SleekSurfaceDark = Color(0xFF141218)
val SleekSurfaceVariantDark = Color(0xFF2B2930)
val SleekPrimaryDark = Color(0xFFD0BCFF)
val SleekOnPrimaryDark = Color(0xFF381E72)
val SleekPrimaryContainerDark = Color(0xFF4F378B)
val SleekOnPrimaryContainerDark = Color(0xFFEADDFF)
val SleekSecondaryDark = Color(0xFFCCC2DC)
val SleekOnSecondaryDark = Color(0xFF332D41)
val SleekSecondaryContainerDark = Color(0xFF4A4458)
val SleekOnSecondaryContainerDark = Color(0xFFE8DEF8)
val SleekTertiaryDark = Color(0xFFEFB8C8)
val SleekTertiaryContainerDark = Color(0xFF633B48)
val SleekOutlineDark = Color(0xFF938F99)
val SleekOutlineVariantDark = Color(0xFF49454F)
val SleekTextPrimaryDark = Color(0xFFE6E1E5)
val SleekTextSecondaryDark = Color(0xFFCAC4D0)

// Quick Stat Badges & Hero Accent Accents (from Sleek Interface design)
val StatCoralBg = Color(0xFFFFDAD6)
val StatCoralFg = Color(0xFF410002)
val StatBlueBg = Color(0xFFD3E4FF)
val StatBlueFg = Color(0xFF001D36)
val StatPurpleBg = Color(0xFFEADDFF)
val StatPurpleFg = Color(0xFF21005D)
val StatGreenBg = Color(0xFFC8E6C9)
val StatGreenFg = Color(0xFF004D20)

// Accent & Status
val SuccessColor = Color(0xFF10B981)
val WarningColor = Color(0xFFF59E0B)
val DangerColor = Color(0xFFB3261E)
val AccentGradientStart = Color(0xFF6750A4)
val AccentGradientEnd = Color(0xFFEADDFF)

